def Motif_Finder(dna_sequence:str,motif_sequence:str)->list:
    """
    Finds the starting position of all the motifs in the dna sequence
    """
    motif_start_index=[]
    
    for nucleotide_index in range(len(dna_sequence)):
        if dna_sequence[nucleotide_index:nucleotide_index+len(motif_sequence)]==motif_sequence:
            motif_start_index.append(nucleotide_index+1)

    return motif_start_index

print(' '.join([str(index) for index in Motif_Finder('CGAAAGTCTACCGAAAGTGTCGAAAGTTCAACCGAAAGTTTACTACGAAAGTCTCCCACGAAAGTCAGCGAAAGTGCACCGAAAGTGGAATTCGAAAGTAGCGAAAGTCTACAGCGAAAGTGTCGAAAGTAACGAAAGTTGCGAAAGTCGAGCGAAAGTTTTTCGAAAGTCGAAAGTCGAAAGTATCGAAAGTACGAAAGTGGGCGAAAGTCGAAAGTTCGAAAGTACGAAAGTCGGCGAAAGTACGACGAAAGTCGAAAGTTTCGAAACGCTCGAAAGTGGCGACGAAAGTCGAAAGTACTCGAAAGTTACGCCGAAAGTCGAAAGTCGAAAGTGAATCGAAAGTAGTCGAAAGTTTGCTACGCGAAAGTGCGAAAGTCAGCGAAAGTTCGAAAGTAAGCGAAAGTCCGAAAGTCGAAAGTCCGCGAAAGTCGAAAGTCGAAAGTTCGAAAGTGAATCGAAAGTCGAAAGTCCACGAAAGTGCAATCTCCGAAAGTATCGAAAGTGGTCGAAAGTTGTGCGAAAGTCGCGAAAGTGCTACGAAAGTCGAAAGTCCTTCGAAAGTTGGTACGAAAGTCTGGCCGAAAGTACCGAAAGTATCGAAAGTCGAAAGTTCTAGCCGAAAGTAGCGAAAGTACCGAAAGTACGAAAGTCGAAAGTCATCGAAAGTCGAAAGTGTCGAAAGTTCGAAAGTGATCCGAAAGTATGCGAAAGTTACGAAAGTATACGAAAGTACGAAAGTTTACCGAAAGTCGAAAGTCGAAAGTAGATCCGAAAGTTCCCGTGCGAAAGTGAGACGAAAGTTCCAAGACATCTATAATCGAAAGTCCGAAAGTCAAGGCCGAAAGTCGAAAGTGTGCGGCGAAAGTACACGCGAAAGTTGGAGTAATTCCGAAAGTGCGAAAGTCGAAAGTCGAAAGTCAA','CGAAAGTCG')]))
# print(Motif_Finder('GATATATGCATATACTT','ATAT'))